openapi: 3.0.0
info:
  title: Sample API
  description: Swagger documentation of COPO/DTOL sample API.
  version: 0.1.1
servers:
  - url: http://0.0.0.0:8000/api
    description: Local Server
  - url: http://0.0.0.0:80/api
    description: Live Server
paths:
  /sample/manifest/{manifest_id}:
    get:
      parameters:
        - name: manifest_id
          in: path
          required: true
          description: uuid of the manifest in question
          schema:
            type: string
            minimum: 1

      responses:
        "200": # status code
          description: A JSON array sample objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
        "400":
          description: invalid manifest_id

  /sample/manifest/{manifest_id}/sample_statuses:
    get:
      parameters:
        - name: manifest_id
          in: path
          required: true
          description: uuid of the manifest in question
          schema:
            type: string
            minimum: 1

    responses:
      "200": # status code
        description: A JSON array sample objects
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
      "400":
        description: invalid manifest_id

  /sample/copo_id/{copo_ids}:
    get:
      parameters:
        - name: copo_ids
          in: path
          required: true
          description: hexadecimal sample ids, separated by commas
          schema:
            type: string
            minimum: 1

      responses:
        "200": # status code
          description: A JSON array sample objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
        "400":
          description: InvalidId found in request

  /sample/biosample_id/{biosample_ids}:
    get:
      parameters:
        - name: biosample_ids
          in: path
          required: true
          description: biosample accessions created by ENA, separated by commas
          schema:
            type: string
            minimum: 1

      responses:
        "200": # status code
          description: A JSON array sample objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'

  /sample/sample_field/{field}/{values}:
    get:
      parameters:
        - name: field
          in: path
          required: true
          description: a known sample field to search for
          schema:
            type: string
            minimum: 1
            maximum: 1
        - name: values
          in: path
          required: true
          description: a comma separated list of values to look for
          schema:
            type: string
            minimum: 1
      responses:
        "200": # status code
          description: A JSON array sample objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'




components:
  schemas:
    SampleStatus:
      type: object
      properties:
        copo_id:
          type: string
          description: unique COPO identifier for this sample
        manifest_id:
          type: string
          description: unique identifier for manifest in which this sample appears
        status:
          type: string
          description: status of this sample. PENDING means waiting for supervisor approval, ACCEPTED means supervisor approval gained, REJECTED means supervisor rejected
        time_verified:
          type: string
          description: when was this sample approved by the dtol_manager
    Sample:
      type: object
      properties:
        SERIES:
          type: string
        RACK_OR_PLATE_ID:
          type: string
        TUBE_OR_WELL_ID:
          type: string
        SPECIMEN_ID:
          type: string
        ORDER_OR_GROUP:
          type: string
        FAMILY:
          type: string
        GENUS:
          type: string
        TAXON_ID:
          type: string
        SCIENTIFIC_NAME:
          type: string
        LIFESTAGE:
          type: string
        SEX:
          type: string
        ORGANISM_PART:
          type: string
        GAL:
          type: string
        GAL_SAMPLE_ID:
          type: string
        COLLECTOR_SAMPLE_ID:
          type: string
        COLLECTED_BY:
          type: string
        COLLECTOR_AFFILIATION:
          type: string
        DATE_OF_COLLECTION:
          type: string
        COLLECTION_LOCATION:
          type: string
        DECIMAL_LATITUDE:
          type: string
        HABITAT:
          type: string
        DESCRIPTION_OF_COLLECTION_METHOD:
          type: string
        EASE_OF_SPECIMEN_COLLECTION:
          type: string
        IDENTIFIED_BY:
          type: string
        IDENTIFIER_AFFILIATION:
          type: string
        IDENTIFIED_HOW:
          type: string
        SPECIMEN_ID_RISK:
          type: string
        PRESERVED_BY:
          type: string
        PRESERVER_AFFILIATION:
          type: string
        PRESERVATION_APPROACH:
          type: string
        TIME_ELAPSED_FROM_COLLECTION_TO_PRESERVATION:
          type: string
        DATE_OF_PRESERVATION:
          type: string
        SIZE_OF_TISSUES_IN_TUBE:
          type: string
        TISSUE_REMOVED_FROM_BARCODING:
          type: string
        PLATE_ID_FOR_BARCODING:
          type: string
        TUBE_OR_WELL_ID_FOR_BARCODING:
          type: string
        TISSUE_FOR_BARCODING:
          type: string
        BARCODE_PLATE_PRESERVATIVE:
          type: string
        PURPOSE_OF_SPECIMEN:
          type: string
        HAZARD_GROUP:
          type: string
        REGULATORY_COMPLIANCE:
          type: string
        VOUCHER_ID:
          type: string
        biosampleAccession:
          type: string
        created_by:
          type: string
        time_created:
          type: string
        submissionAccession:
          type: string
        sraAccession:
          type: string
        manifest_id:
          type: string
        time_verified:
          type: string
        verified_by:
          type: string
        copo_id:
          type: string
        status:
          type: string