# Generated by Django 3.1 on 2022-06-23 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_copo', '0005_auto_20201207_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatusMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_task', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(default='All Tasks Complete', max_length=500)),
                ('message_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_copo.userstatusmessages')),
            ],
        ),
    ]
