# Generated by Django 3.1 on 2022-06-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('web_copo', '0006_statusmessage_userstatusmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='active_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='message_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_copo.userdetails'),
        ),
        migrations.DeleteModel(
            name='UserStatusMessages',
        ),
    ]
