# Generated by Django 3.1 on 2022-06-24 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web_copo', '0007_auto_20220623_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusmessage',
            options={'get_latest_by': 'created'},
        ),
    ]
