# Generated by Django 3.1 on 2022-06-24 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_copo', '0008_auto_20220624_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='message_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
