# Generated by Django 3.1 on 2022-08-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_copo', '0009_auto_20220624_1801'),
        ('web_copo', '0007_auto_20220803_0930'),
    ]

    operations = [
    ]
