# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os

class TestCopoergap02():
  @classmethod
  def setup_class(cls):
    cls.driver = webdriver.Chrome()
    cls.vars = {}

  @classmethod
  def teardown_class(cls):
    cls.driver.quit()
  
  def test_login(self):
    self.driver.get("http://127.0.0.1:8000/copo")
    self.driver.set_window_size(1188, 839)
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "password")))
    self.driver.find_element(By.ID, "password").send_keys("Iam1testUser")
    self.driver.find_element(By.ID, "username").send_keys("debby.ku@earlham.ac.uk")
    self.driver.find_element(By.CSS_SELECTOR, "#signin-button > .mat-button-wrapper").click()
    time.sleep(5)
    elements = self.driver.find_elements(By.XPATH, "//span[contains(.,\'Work Profiles\')]")
    assert len(elements) > 0
  
  def test_createERGAProfile(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1188, 839)
    self.driver.find_element(By.CSS_SELECTOR, ".new-component-template > .icon").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "copo.profile.title")))
    self.driver.find_element(By.ID, "copo.profile.title").click()
    self.driver.find_element(By.ID, "copo.profile.title").send_keys("test ERGA ")
    self.driver.find_element(By.ID, "copo.profile.description").click()
    self.driver.find_element(By.ID, "copo.profile.description").send_keys("test ERGA profile")
    dropdown = self.driver.find_element(By.ID, "copo.profile.type")
    dropdown.find_element(By.XPATH, "//option[. = 'European Reference Genome Atlas (ERGA)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".copo-components-icons").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(.,\'test ERGA profile\')]")))
  
  def test_uploadERGAManifest(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1188, 840)
    self.driver.find_element(By.XPATH, "//div[div=\"test ERGA profile\"][1]/span[1]/div[1]").click()
    self.driver.find_element(By.LINK_TEXT, "Submit ERGA Manifest").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pink > .icon").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[contains(.,\'Ok\')]")))
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Ok\')]").click()
    self.driver.find_element(By.ID, "file").send_keys(f"{os.getcwd()}/data/copo-erga-p02.xlsx")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//label[@id=\'files_label\' and not(contains(@class,\'disabled\'))]")))
    elements = self.driver.find_elements(By.XPATH, "//button[@id=\'export_errors_button\' and not(contains(@style,\'display:none\'))]")
    assert len(elements) == 0
    self.driver.find_element(By.ID, "permits").send_keys(f"{os.getcwd()}/data/ERGA_PI_7940_01_SAMPLING_PERMITS.pdf")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[@id=\'finish_button\' and not(contains(@style,\'display:none\'))]")))
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'ERGA_PI_7940_01_SAMPLING_PERMITS.pdf\')]")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, "#permits_table td:nth-child(3)").text == ""
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//button[@id=\'finish_button\' and not(contains(@style,\'display:none\'))]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[3]/div/div/button[2]")))
    self.driver.find_element(By.XPATH, "//div[3]/div/div/button[2]").click()
    elements = self.driver.find_elements(By.XPATH, "//span[contains(.,\'Samples\')]")
    assert len(elements) > 0
  
  def test_approveSamples(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1200, 1011)
    self.driver.find_element(By.CSS_SELECTOR, "#accept_reject_shortcut > .icon").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//td[contains(.,\'test ERGA\')]")))
    self.driver.find_element(By.XPATH, "//td[contains(.,\'test ERGA\')]").click()
    elements = self.driver.find_elements(By.LINK_TEXT, "Pending Samples")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".form-check-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".positive").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[contains(.,\'Ok\')]")))
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Ok\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//p[starts-with(.,\'Querying Public Naming Service\')]")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//p[starts-with(.,\'Last Sample Submitted\')]")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//p[starts-with(., \'Bioimage not submitted\')]")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".dataTables_empty")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Processing Samples").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".dataTables_empty")))
    self.driver.find_element(By.LINK_TEXT, "Accepted Samples").click()
    elements = self.driver.find_elements(By.XPATH, "//div[2]/table/tbody/tr/td")
    assert len(elements) > 0
  
  def test_logout(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1188, 839)
    self.driver.find_element(By.CSS_SELECTOR, ".caret").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(7) .icon_text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.get("https://orcid.org/signout")
  
