# Generated by Selenium IDE
import pytest
import time
import json
import subprocess
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import string
import random
def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
   return ''.join(random.choice(chars) for _ in range(size))

class TestCopoassemblyf01():
  @classmethod
  def setup_class(cls):
    cls.driver = webdriver.Chrome()
    cls.vars = {}

  @classmethod
  def teardown_class(cls):
    cls.driver.quit()
  
  def test_login(self):
    self.driver.get("http://127.0.0.1:8000/copo")
    self.driver.set_window_size(1188, 839)
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "password")))
    self.driver.find_element(By.ID, "password").send_keys("Iam1testUser")
    self.driver.find_element(By.ID, "username").send_keys("debby.ku@earlham.ac.uk")
    self.driver.find_element(By.CSS_SELECTOR, "#signin-button > .mat-button-wrapper").click()
    time.sleep(5)
    elements = self.driver.find_elements(By.XPATH, "//span[contains(.,\'Work Profiles\')]")
    assert len(elements) > 0
  
  def test_createstandaloneProfile(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1188, 839)
    self.driver.find_element(By.CSS_SELECTOR, ".new-component-template > .icon").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "copo.profile.title")))
    self.driver.find_element(By.ID, "copo.profile.title").click()
    self.driver.find_element(By.ID, "copo.profile.title").send_keys("test Assembly")
    self.driver.find_element(By.ID, "copo.profile.description").click()
    self.driver.find_element(By.ID, "copo.profile.description").send_keys("test Assembly profile")
    self.driver.find_element(By.CSS_SELECTOR, ".copo-components-icons").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(.,\'test Assembly profile\')]")))
  
  def test_uploadreads(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1188, 840)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[1]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Submit Reads")))
    self.driver.find_element(By.LINK_TEXT, "Submit Reads").click()
    self.driver.find_element(By.ID, "presigned_urls_modal_button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "url_text_area")))
    self.driver.find_element(By.ID, "url_text_area").send_keys("Cafeteria_transcriptome.fasta.gz\nfile001.fastq.gz\nfile0010.fastq.gz\nfile003.fastq.gz\nfile004.fastq.gz\nfile005.fastq.gz\nfile006.fastq.gz\nfile007.fastq.gz\nfile008.fastq.gz\nfile009.fastq.gz\nsmall1_r1.fastq.gz\nsmall1_r2.fastq.gz\nsmall2_r1.fastq.gz\nsmall2_r2.fastq.gz")
    self.driver.find_element(By.ID, "process_urls_button").click()
    #WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\"command_area\" and contains(., \'Please wait\')]")))
    WebDriverWait(self.driver, 180).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\"command_area\" and contains(., \'nohup curl\')]")))
    self.driver.find_element(By.ID, "copy_urls_button").click()
    time.sleep(1)
    cmd = f"cd {os.getcwd()}/data/reads && "
    cmd = cmd + self.driver.find_element(By.ID, "command_area").text
    cmd = cmd.replace("nohup", "")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    receipt = subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)
    if str(receipt).count("HTTP/1.1 200 OK") != 14:
        print(receipt)  
        assert False

  def test_uploadmanifest(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1512, 944)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[1]").click()
    self.driver.find_element(By.LINK_TEXT, "Submit Reads").click()
    self.driver.find_element(By.ID, "file").send_keys(f"{os.getcwd()}/data/reads/ENA_Manifests/ena1_single_sequence_reads_manifest.xlsx")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//table[@id=\'sample_parse_table\']/tbody/tr/td")))
    self.driver.find_element(By.ID, "ena_finish_button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".page-title-custom")))
  
  def test_submitManifest(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1512, 944)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[2]").click()
    self.driver.find_element(By.XPATH, "//span[@class=\'pcomponent-name\' and contains(., \'Submission\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//span[@class=\'page-title-custom\' and contains(., \'Submissions\')]")))
    self.driver.find_element(By.XPATH, "//div[@class=\'ui active buttons\']").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@data-task=\'submit\' and contains(., \'Submit\') and not (contains(@class, \'disabled\'))]")))
    self.driver.find_element(By.XPATH, "//div[@data-task=\'submit\' and contains(., \'Submit\') and not (contains(@class, \'disabled\'))]").click()
    WebDriverWait(self.driver, 180).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(., \'Submission completed.\')]")))
  
  def test_checkAccession(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1512, 944)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[2]").click()
    self.driver.find_element(By.XPATH, "//span[@class=\'pcomponent-name\' and contains(., \'Submission\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//span[@class=\'page-title-custom\' and contains(., \'Submissions\')]")))
    self.driver.find_element(By.XPATH, "//div[@class=\'ui active buttons\']").click()
    self.driver.find_element(By.XPATH, "//div[@data-task=\'view_accessions\' and contains(., \'View Accessions\') ]").click()
    
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'PRJ\')] ")))
    elements = self.driver.find_elements(By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'ERX\')] ")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'ERR\')] ")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'ERS\')] ")
    assert len(elements) > 0
  
  def test_submitassemblyvalidationatleastonfile(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1920, 1055)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[1]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Submit Assembly")))
    self.driver.find_element(By.LINK_TEXT, "Submit Assembly").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.ID, "id_assemblyname")))
    elements = self.driver.find_elements(By.XPATH, "//input[@id=\'id_study\' and contains(@value, \'PRJ\')]")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "id_assemblyname").send_keys("test " + id_generator())
    self.driver.find_element(By.ID, "id_coverage").send_keys("1")
    self.driver.find_element(By.ID, "id_program").send_keys("test")
    self.driver.find_element(By.ID, "id_platform").send_keys("test")
    self.driver.find_element(By.ID, "submit_assembly_button").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(@class, \'alert\') and contains(., \'At least one assembly file is required\')]")))
  
  def test_submitassemblyvalidationmandatoryfield(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1920, 1055)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[1]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Submit Assembly")))
    self.driver.find_element(By.LINK_TEXT, "Submit Assembly").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.ID, "id_assemblyname")))
    elements = self.driver.find_elements(By.XPATH, "//input[@id=\'id_study\' and contains(@value, \'PRJ\')]")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "submit_assembly_button").click()
    WebDriverWait(self.driver, 15).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@class=\"errorlist\"]/li[contains(., \"assemblyname\")]")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@class=\"errorlist\"]/li[contains(., \"coverage\")]")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@class=\"errorlist\"]/li[contains(., \"program\")]")))
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//ul[@class=\"errorlist\"]/li[contains(., \"platform\")]")))
  
  def test_submitassembly(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1920, 1055)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[1]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "Submit Assembly")))
    self.driver.find_element(By.LINK_TEXT, "Submit Assembly").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.ID, "id_assemblyname")))
    elements = self.driver.find_elements(By.XPATH, "//input[@id=\'id_study\' and contains(@value, \'PRJ\')]")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "id_assemblyname").send_keys("test " + id_generator())
    self.driver.find_element(By.ID, "id_coverage").send_keys("1")
    self.driver.find_element(By.ID, "id_program").send_keys("test")
    self.driver.find_element(By.ID, "id_platform").send_keys("test")
    self.driver.find_element(By.ID, "id_fasta").send_keys(f"{os.getcwd()}/data/reads/Cafeteria_transcriptome.fasta.gz")
    self.driver.find_element(By.ID, "submit_assembly_button").click()
    WebDriverWait(self.driver, 60).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(., \"Validating Assembly Submission\")]")))
    WebDriverWait(self.driver, 180).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(., \"Submitting Assembly\")]")))
    WebDriverWait(self.driver, 120).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(., \"The assembly has been created with accession\")]")))
  
  def test_checkAccessionwithassembly(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1512, 944)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[2]").click()
    self.driver.find_element(By.XPATH, "//span[@class=\'pcomponent-name\' and contains(., \'Submission\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//span[@class=\'page-title-custom\' and contains(., \'Submissions\')]")))
    self.driver.find_element(By.XPATH, "//div[@class=\'ui active buttons\']").click()
    self.driver.find_element(By.XPATH, "//div[@data-task=\'view_accessions\' and contains(., \'View Accessions\') ]").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'PRJ\')] ")))    
    elements = self.driver.find_elements(By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'ERX\')] ")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'ERR\')] ")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'ERS\')] ")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//table[contains(@id, \'submission_accessions_view_tbl\')]/tbody//tr/td[1][starts-with(., \'ERZ\')] ")
    assert len(elements) > 0
  
  def test_uploadmanifest2(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1512, 944)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[1]").click()
    self.driver.find_element(By.LINK_TEXT, "Submit Reads").click()
    self.driver.find_element(By.ID, "file").send_keys(f"{os.getcwd()}/data/reads/ENA_Manifests/ena1_sequence_reads_manifest.xlsx")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//table[@id=\'sample_parse_table\']/tbody/tr/td")))
    self.driver.find_element(By.ID, "ena_finish_button").click()
  
  def test_uploadmanifest3(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1512, 944)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[1]").click()
    self.driver.find_element(By.LINK_TEXT, "Submit Reads").click()
    self.driver.find_element(By.ID, "file").send_keys(f"{os.getcwd()}/data/reads/ENA_Manifests/ena1_single_sequence_reads_manifest.xlsx")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//table[@id=\'sample_parse_table\']/tbody/tr/td")))
    self.driver.find_element(By.ID, "ena_finish_button").click()
  
  def test_submitManifest2(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1512, 944)
    self.driver.find_element(By.XPATH, "//div[div=\"test Assembly profile\"][1]/span[1]/div[2]").click()
    self.driver.find_element(By.XPATH, "//span[@class=\'pcomponent-name\' and contains(., \'Submission\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//span[@class=\'page-title-custom\' and contains(., \'Submissions\')]")))
    self.driver.find_element(By.XPATH, "//div[@class=\'ui active buttons\']").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@data-task=\'submit\' and contains(., \'Submit\') and not (contains(@class, \'disabled\'))]")))
    self.driver.find_element(By.XPATH, "//div[@data-task=\'submit\' and contains(., \'Submit\') and not (contains(@class, \'disabled\'))]").click()
    WebDriverWait(self.driver, 240).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(., \'Submission completed.\')]")))

  
  def test_logout(self):
    self.driver.get("http://127.0.0.1:8000/copo/")
    self.driver.set_window_size(1188, 839)
    self.driver.find_element(By.CSS_SELECTOR, ".caret").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(7) .icon_text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.get("https://orcid.org/signout")
  
